### ISSUE TITLE
Allocation Preview fails with available inventory

### ISSUE THREAD

**Issue by svevang** [PRX/grove.prx.org#102]
```
Having 1 flight for an inventory,
having 100k allocated and flight saved,
See 200k total inventory,
adjust the flight's goal to > 100K available inventory
receive 422 Error: Flight goal is greater than total available
```

The issue is tied up in the preview of a new versus saved flight.  There are two routes:
First one is for unsaved flights:
`/api/:api_version/flights/preview`
Second one is for saved/persisted flights (with flight `:id`)
`/api/:api_version/flights/:id/preview`

In the case where we use the unsaved preview with a saved flight, this creates a new flight + allocation, so for a brief time in the WAL there are 2 flights each with allocations draining the available inventory.

The solution is to use the API resource for saved flights, which will preview the allocation on the existing flight, removing the existing allocations (freeing up inventory), allocating and then rolling back.

Could take in a flight object here (or maybe a new method?):
https://github.com/PRX/grove.prx.org/blob/master/src/app/core/allocation/allocation-preview.service.ts#L14

**Comment by sandikbarr** [comment]
Good find. Seems like this won't be too difficult to address. Thanks for sorting it out!
