### ISSUE TITLE
Lower bound date on date picker is inclusive to match flight start/end

### ISSUE THREAD

**Issue by svevang** [PRX/grove.prx.org#114]
Seeing the lower bound on the flight is exclusive, unlike the flight. Flight start and end are `[)` as in lower bound inclusive and upper bound exclusive.

Could be surprising, e.g. in the case where I mark the flight to start on e.g. Monday, but then it begins serving when Monday is over.

**Comment by svevang** [comment]
Flights date range in the UI:

![Screen Shot 2020-02-03 at 2.40.46 PM.png](https://images.zenhubusercontent.com/5b4d14bd183c8728de34324d/d9255128-5755-4096-ba35-9363e092347d)

And here is the flight representer embedded in the campaign:

![Screen Shot 2020-02-03 at 2.41.34 PM.png](https://images.zenhubusercontent.com/5b4d14bd183c8728de34324d/8229bfc7-ca0b-47e1-b8db-0e62f29e3c09)

Here is the url that the preview hits:

![Screen Shot 2020-02-03 at 2.42.33 PM.png](https://images.zenhubusercontent.com/5b4d14bd183c8728de34324d/130e62de-4a7f-48b5-b1a6-9b729581eff2)

**Comment by sandikbarr** [comment]
Perhaps also related is the validation on the start and end date. Even without the custom date range picker, angular material supports min/max date out of the box.

**Comment by sandikbarr** [comment]
Thinking about this dates off by one issue, it's very likely an issue with timezones since a UTC date at midnight falls one date prior for our US based timezones.
