### ISSUE TITLE
Available inventory UI for in-progress flights.

### ISSUE THREAD

**Issue by svevang** [PRX/grove.prx.org#121]
Per discussion here:
https://prx.slack.com/archives/GCEJE5136/p1580841990007400

There are a couple UI use-cases that make it hard to understand what inventory is available. To investigate:

- Flight is partially complete: The available inventory column should not take into account inventory that's in the past, and should indicate which goals are 'discarded' (not summed into the current goal).

- Multi zone flights w/ single creative. Look at the `Flight#total_inventory` as a single top level 'what's-available' available inventory number to provide the user.  Could also be used in the case of companion (e.g. a single calculation of many companion ads/impressions you can run).

**Comment by brandonhundt** [comment]
![Screen Shot 2020-02-20 at 2.37.25 PM.png](https://images.zenhubusercontent.com/5bd1dc3a4cadef67d2695e38/dc3cefb9-d4b3-42f2-92e4-2f107d5e4edd)

Proposal:

1. Once a flight leaves preview allocation, the Goal column becomes 'Allocated'. This total remains when flights are in progress so the allocated (ie forecast minus what is reserved) can be seen as actuals roll in.
2. Availability column zeros out when the actual date has passed (even when the date is broken out -- today = 0, yesterday = 0)
3. Actual column appears as actuals appear in the system.
4. Zones are rolled up

Essentially we are adding one more column

**Comment by brandonhundt** [comment]
Finalized version:

With a flight status label:
![Screen Shot 2020-02-27 at 1.15.18 PM.png](https://images.zenhubusercontent.com/5bd1dc3a4cadef67d2695e38/e95a1638-0029-48cc-a596-dfe2ea5cc68b)

Expanded
![Screen Shot 2020-02-27 at 1.57.27 PM.png](https://images.zenhubusercontent.com/5bd1dc3a4cadef67d2695e38/91f97c61-d133-415e-9c37-30eeb8a2a5ed)
