### ISSUE TITLE
Add actuals and flight-status to the dashboard

### ISSUE THREAD

**Issue by brandonhundt** [PRX/grove.prx.org#138]
Where the Goal column exists now:
![Screen Shot 2020-02-28 at 9.50.59 AM.png](https://images.zenhubusercontent.com/5bd1dc3a4cadef67d2695e38/8ee7cac3-4360-4889-9c13-26f58af8dd17)

Also add 2 more columns:
- Actuals (_NOT SORTABLE_)
  - it's the flight `actualCount`
- Flight Status (whether the last allocation-engine cron succeeded or failed.  In other words ... do we have a _plan_ to meet the totalGoal or not).
  - it's the flight `status` and/or `statusMessage`.  The status will be `"ok"` or `"error"`, and the `statusMessage` blank/null or a fairly long and descriptive string.  May be shortest/best to just capitalize `status` that and throw it in the column.
  - TODO: @cavis needs to make this sortable (1-liner in augury)

And then using simple mathematic equations of summation [ie addition] provide the total for actuals / totalGoals in a new table header row. (not in the footer.)

**Comment by cavis** [comment]
Note: there are some API issues with this.

- Availability currently requires N+1 GETs to a different endpoint.  We could add it to the flight JSON responses, but it would still be N+1 db queries.  (And it would slow down all flight responses).  Making it sortable is a whole other thing (lot of db join trickery required).
- You can get allocated by summing each `flight.allocation[].goalCount` right now.  But you can't sort - and it would take some work to support that.
- Actuals are a direct attribute on the `flight.actualCount`.  But would take some work to support sorting.

Also seems like we'd want to leave the goals in here somewhere?  Other ad platforms at least tell you the number of actuals vs the goal - `600 / 1200`.

**Comment by cavis** [comment]
Ticket updated to reflect new requirement.
