### ISSUE TITLE
CSV Flight Report

### ISSUE THREAD

**Issue by brandonhundt** [PRX/grove.prx.org#143]
Follow the campaign report CSV example, but limit it to a single flight. 

Add a download link to the end of the flight table on the inventory flight dashboard.

https://docs.google.com/spreadsheets/d/1yA8cKCANS-V-2Sw4EXPrSWQ-LCx0VocnVfSxMoU6NX0/edit#gid=176452782

**Comment by cavis** [comment]
NOTE: there are a few things in the CSV we may be waiting on advanced-targeting for (there isn't an API yet for Augury flight-targets, etc).  But it seems like most of this data exists in the API, and we can open tickets for anything you find missing.

**Comment by brandonhundt** [comment]
Issue moved to [PRX/augury.prx.org #608](https://github.com/PRX/augury.prx.org/issues/608) via [**ZenHub**](https://www.zenhub.com/)
