### ISSUE TITLE
RESEARCH: Flight zone file uploader 

### ISSUE THREAD

**Issue by cavis** [PRX/grove.prx.org#151]
Ability to upload creatives directly from the app, instead of pasting in URLs.

I'm not exactly sure how we want to do this?  The URL definitely needs to be permanently available, so the `prx-up` + Evaporate.js thing we've done in the past may not be ideal.

Maybe a different S3 bucket that files are permanent in?  Or we build some sort of "copy S3 file to my permanent bucket" worker in Augury.  But I've been trying to avoid that so far.

**Comment by cavis** [comment]
TODO: research some other ways to do this.  We want to upload to S3 via Evaporate (or something).  And validate it's an actual/valid mp3.  So probably involves Porter at some level.

Could we somehow directly invoke Porter and validate?  Without an Augury status field in the db and porter-callback-worker?  Or is there some 3rd party thing we don't know about?

**Comment by cavis** [comment]
Some updates, since I'll forget all these things over the weekend...

Looked at a few libraries:

- [Dropzone.js](https://www.dropzonejs.com/) seems pretty popular. But maybe less featured than the others - and a lot of things we want to do would be DIY.  Didn't see any S3-multipart.
- [Filepond](https://pqina.nl/filepond/) looks nice. Image editor is _reeeeal_ nice. Has an angular "adapter". Doesn't seem to have S3 multipart.
- [Uppy](https://uppy.io/) has a slightly unmaintained ngrx store, and a slightly better maintained angular package.
  - Has multipart S3 uploads, though not the CloudFront stuff.  But in my experience, an accelerated S3 bucket is almost as good.
  - With the "companion server" you can do cool bypass client stuff, uploading from google drive, dropbox, etc. 
  - So we'd want to run the [companion](https://uppy.io/docs/companion/) server somewhere. Could dockerize it or I've seen some lambda examples.
  - Or short term, seems like we could just use the current upload lambda to sign our multipart uploads.

So I guess Uppy is the clear winner on that front.

The other thing I need to look into here: a better frontend Mp3 validation library.  So we can avoid an async `audio_file.status` validation in Augury.  (It's sort of annoying in Publish/CMS to have to wait for that Porter callback to really know if it's valid or not).

**Comment by kookster** [comment]
spent more time than I should have looking at tricks to look at audio in the browser, this seems like the best I have found https://mediainfo.js.org/
Weighs in at about 1.2 mb but works really fast - I can only guess it only reads header info on files, not the whole thing

**Comment by cavis** [comment]
From #tech-grove ... a better option would probably be this [music-metadata-browser](https://github.com/Borewit/music-metadata-browser) project.  More active development, and could probably extend the analysis code to support our broadcast files.

And has an [example angular project](https://github.com/Borewit/audio-tag-analyzer).

**Comment by kookster** [comment]
yeah, I like that one (music-metadata-browser).
Read the typescript code, seems very well made.
