### ISSUE TITLE
Advertiser industry info

### ISSUE THREAD

**Issue by cavis** [PRX/grove.prx.org#153]
Implement the frontend for the advertiser industry-info page.  Needs #152 and PRX/augury.prx.org#200.  All fields _except_ the advertisers-on-same-downloads.  Leave that for later.

https://user-images.githubusercontent.com/1410587/77201186-ae0c0380-6ab1-11ea-94d3-d401b08213c4.png

https://sketch.cloud/s/WlAj8/a/0VgK5G

**Comment by brandonhundt** [comment]
Closing in favor of https://github.com/PRX/augury.prx.org/issues/585
