### ISSUE TITLE
Define common terminology used in the app.

### ISSUE THREAD

**Issue by brandonhundt** [PRX/grove.prx.org#155]
Would be helpful if we had this to:

1. Ensure we are on the same page in discussion.
2. Creating help documentation

Terms include, but not exclusive to:
- Inventory
- Campaign
- Flight
- Forecast
- Actual
- Allocation
- Availability

**Comment by cavis** [comment]
https://docs.google.com/document/d/1DewEQ6oQjUuC-yLa94vKUycfz43G-wG8p1e8nyhpvew/edit?ts=5e8631a6#
