### ISSUE TITLE
Inventory table zones rollup

### ISSUE THREAD

**Issue by sandikbarr** [PRX/grove.prx.org#170]
Inventory table zones should be rolled up and displayed together as a single table

**Comment by cavis** [comment]
PRX/augury.prx.org#205 should do this at the API level.  (Returning a single `days: []` array, already rolling up all zones).

**Comment by sandikbarr** [comment]
ah, excellent. so it will just have to roll up the allocation previews, right?

**Comment by cavis** [comment]
The theory is that `GET /api/v1/flights/1234` and `POST /api/v1/flights/1234/preview` will return exactly the same JSON.  (The latter is just _pretending_ you did a PUT to the flight, rendering the json, and rolling back the DB before returning).  So you shouldn't need to do anything different.

I'm not exactly sure how to handle that at the ngrx level ... could just patch the `flight.days` returned from the preview onto the localFlight?  Or a separate preview-store could make more sense.

**Comment by sandikbarr** [comment]
Cool.

So for flights that have not yet been created, do we still use the existing allocation preview endpoint? How about inventory availability preview on those flights that havent been created?

**Comment by cavis** [comment]
Yep, for brand new flights, you can use the `prx:flight-allocation-preview` off the campaign.  So it ends up being `POST /api/v1/campaigns/1234/flights/preview` ... with the same params you would have posted to `/api/v1/campaigns/1234/flights` to create + persist the new flight.

I sort of expect we'll stop using the `/api/v1/inventory/1234/availability` endpoint entirely.  At least for now - it may come back for some dashboard charts.  Everything that flight table needs should come out of that single flight JSON.

**Comment by sandikbarr** [comment]
I'm thinking a separate preview store is still what makes sense. Even with the available, allocated, and actual coming from the flights API, I will put those in their own store to prevent the reducers from having deep objects. I diagramed out the general shape of the NgRx stores here, what we have currently vs with the API changes for temporary and persisted flights.

**Currently**
- Campaign
  - Flights
    - temporary flights with timestamps for ids
      - Availability (without flightId)
      - Allocation Preview
    - flights that have been persisted
      - Availability (with flightId)
      - Allocation Preview

**Preview API**
- Campaign
  - Flights
    - temporary flights with timestamps for ids
      - Preview `/api/v1/campaigns/1234/flights/preview`
    - flights that have been persisted
      - Preview `/api/v1/flights/1234/preview`
      - Availability from flight.days
