### ISSUE TITLE
Advertiser type-ahead creates too easily

### ISSUE THREAD

**Issue by cavis** [PRX/grove.prx.org#173]
I keep creating too many advertisers due to this bug.

1. Navigate to "add a new campaign"
2. Focus the advertiser field
3. Type "ryan adds" (a partial piece of an existing advertiser name ... must be incomplete so the "add advertiser" button is showing up in the field)
4. Hit up/down arrows to highlight `"Ryan adds an advertiser"`
5. Press enter

Expected: selects existing advertiser
Actual: creates a new advertiser, but also clears the field for some reason

http://cav.is/iKtDorr.mp4

**Comment by sandikbarr** [comment]
will be replaced by advertiser metadata
