### ISSUE TITLE
Timepicker investigation

### ISSUE THREAD

**Issue by brandonhundt** [PRX/grove.prx.org#178]
This would solve issues relating to fudging the exclusive end date and unlock the ability to let a user pick the time in a specific timezone

How do we build it?
Will this be related to issues we are having now?

**Comment by sandikbarr** [comment]
UTC support for the datepicker is built into Angular Material with the MomentDateAdapter. If we want the user to have the ability to select the timezone (for starting campaigns at midnight Eastern), we need to implement our own DateAdapter.

The flight end date will be "fudged" to appear inclusive with #175

**Comment by brandonhundt** [comment]
Closing in favor of Augury timepicker work.
