### ISSUE TITLE
Change order of flight table columns on dashboard

### ISSUE THREAD

**Issue by brandonhundt** [PRX/grove.prx.org#190]
- C. Status
- F. Status
- Campaign Name
- Start
- End
- Actuals
- Goal
- Advertiser
- Show
- Zone
- Geotarget
- Type
- Rep

**Comment by rpeterman-gp** [comment]
@brandonhundt This columns listed in the ticket seem to be missing the Flight Name. Is it supposed to be not shown, or should it remain first and this list is for the order of the remaining columns?
