### ISSUE TITLE
Untouched new flight looks valid

### ISSUE THREAD

**Issue by cavis** [PRX/grove.prx.org#199]
Steps:

1) new campaign
2) new flight
3) back to campaign form - fill out
4) click save
5) “Campaign Forbidden” error message, but you stay on the `/campaign/new` page.

Expected:

- [ ] Dismissible error message thing for error on save
- [ ] Still attempt to redirect to the new campaign if a flight errors (it's much more common for us to see flight errors than campaign - and it's easy to lose track of the campaign if it has no flights attached)
- [x] Make sure new/untouched flight forms look invalid by default somehow.

**Comment by sandikbarr** [comment]
error handling moved to #222
