### ISSUE TITLE
Campaign Dashboard Filtering

### ISSUE THREAD

**Issue by sandikbarr** [PRX/grove.prx.org#21]
* Filter the campaign dashboard by
  * [x] Flight Date
  * [x] Flight Show
  * [x] Flight Zones
  * [ ] Flight Priority
  * [x] Flight Geolocation 
  * [ ] Campaign Name
  * [x] Advertiser
  * [x] Campaign Rep

* [x] Paging not yet working in API when implemented, also complete/enhance paging.

* [x] Filters should apply to route and when navigating back to the home page in the application or using the back button, the filters should still be applied

**Comment by sandikbarr** [comment]
Hey @cavis, thought you grabbed this ticket for the API, so I created another one #28. Do we have a duplicate or did you mean to close this with the augury filter facets?

**Comment by cavis** [comment]
Whoops!  Didn't mean to close this one ... I think I connected that PR to this Grove issue instead of an Augury one.

**Comment by cavis** [comment]
Also, paging should all work with these filter params.  And they can all be found here: https://github.com/PRX/augury.prx.org/blob/master/app/controllers/api/campaigns_controller.rb#L5

**Comment by sandikbarr** [comment]
K, I'm gonna take this one back and close #28 as dupe. Yeah, I think it was just that paging wasn't implemented yet when I added it on the front end.
