### ISSUE TITLE
UX for bandit allocations

### ISSUE THREAD

**Issue by cavis** [PRX/grove.prx.org#212]
Use case (describe in ad-ops meeting as "a baked-in flight with a goal):

- You've got a bunch of lower-priority flights running in preroll next week.  But they last for months, so no rush.
- We get an order for a high-priority next week.  We want to serve on every download until we hit 10K, then stop.  And go back to serving the lower-priority flights.
- How to set this up through the Grove UI?

Was suggested we use a "Simulate Baked-In" flight _with_ a total_goal (which is currently not allowed on that type).  We could allow that, but the danger is that the flight finishes early then leaves a big gap serving nothing.  Since we pushed the lower-priority flight allocations out of those days.

Maybe instead, you setup a "serve as fast as possible" flight on the frontend, that _steals_ allocations from those lower-priority flights on creation?  Then Augury attempts to push out those other lower-priority allocations, and if unable to, sets those flight statuses to error so ad-ops knows to go manually fix.

**Comment by brandonhundt** [comment]
@cavis I've been thinking more about these bandit flights and I keep coming back to something you mentioned in a previous conversation.

I don't think we need another "flight type", but a checkbox or setting that tells the allocation what to do with other flights. Its a priority lever that we were hoping to avoid, but I think it could make sense without having to set up a new type.

Like a booleen field: "Steal allocations from existing flights" - that triggers a reallocation of existing flights. 

And either way, we may want to consider adding something below the impression table that shows other flights also targeted in the range. (maybe. Ad/Ops can use the dashboard for now)

**Comment by cavis** [comment]
Yeah, it really is a workflow optimization, not a database field.  Currently you would:

- Find all other conflicting flights in this date/range zone
- Set all conflicting-flight Total Goals temporarily to 0.
- Create my new flight (there's nothing competing with it, so it gets whatever allocations it wants).
- Set all conflicting-flight Total Goals back to what I actually want.
- Fix any now unfulfilled flights.

But that's really a pain.  So would be easier to have a 2nd button ... "Save" vs "Save-and-steal-allocations".  It's a one-time action.  If I come back to the flight later, there's no indication that it stole those allocations.

Preview gets tricky.

**Comment by cavis** [comment]
Usurped by #260 !
