### ISSUE TITLE
Dashboard date range filters aren't filtering to correct flights

### ISSUE THREAD

**Issue by brandonhundt** [PRX/grove.prx.org#216]
From Madeleine:
> it seems like the date range selection at the top of the dashboard doesn’t haven’t any affect on the flights shown? I changed it to 06/01 and it is still showing everything. 

Occurring:

1. Filter to start date of 6/1 and end date of 6/30
2. Note that after the flights refresh, flights with dates in December are present.

Expected
1. Filter to start date of 6/1 and end date of 6/30
2. Only flights in that date range should be present.

**Comment by cavis** [comment]
Looks like we never implemented the `before / after` Flight filters in Augury.  (It _is_ implemented on Campaigns ... just not Flights).

**Comment by brandonhundt** [comment]
wrong repo. Closing
