### ISSUE TITLE
Creative Management flight form UI

### ISSUE THREAD

**Issue by IcusFMagni** [PRX/grove.prx.org#226]
Management of Creatives.  This includes files, pingbacks.

**Comment by brandonhundt** [comment]
@IcusFMagni -- What is this ticket about? How can I help?

**Comment by brandonhundt** [comment]
This is the phase 1 version of the design:

![Screen Shot 2020-07-16 at 10.42.27 AM.png](https://images.zenhubusercontent.com/5bd1dc3a4cadef67d2695e38/307a8532-8beb-4625-9ce1-b4d2791bd762)

See: https://www.sketch.com/s/add11476-b42d-44cc-a705-8d2bde1f3f69/a/0E4mAj

I think I know where to head with this ticket. We will need to do file management in a flyout... I'll jump on it.

**Comment by brandonhundt** [comment]
See this thread for updates: https://prx.slack.com/archives/GCEJE5136/p1594920798003900

**Comment by brandonhundt** [comment]
Alright, Alright, Alright. Here is the latest batch of designs for Creative Management:

1. Dashboard, follow the patterns for the flight/campaign dashboard:
![DT - Creative Dashboard.png](https://images.zenhubusercontent.com/5bd1dc3a4cadef67d2695e38/6711ec7d-42d4-4a5a-aa00-d932852cc175)

2. Standalone Creative form (Note: once a file is uploaded, allow a standard audio player to appear to preview the file):
![DT - Add Creative.png](https://images.zenhubusercontent.com/5bd1dc3a4cadef67d2695e38/600f0e63-a2f1-4f63-8415-eaf6480a6e9b)

3. Add a creative through the Flight form: 
![DT - Creatives - Full Add new.jpg](https://images.zenhubusercontent.com/5bd1dc3a4cadef67d2695e38/7b73d4af-04a7-4084-a479-b05dfcb52d6d)

4. Add an existing creative through the flight form:
![DT - Creatives - Full -existing.jpg](https://images.zenhubusercontent.com/5bd1dc3a4cadef67d2695e38/ba7850d0-d622-4f5f-8a5e-a0792f3bf11f)

**Comment by brandonhundt** [comment]
updated designs for Adding a Creative and the dashboard.

![DT - Add Creative.png](https://images.zenhubusercontent.com/5bd1dc3a4cadef67d2695e38/07b0beb5-58bf-493f-bbf7-74d2a54d29c4)

![DT - Add Creative.png](https://images.zenhubusercontent.com/5bd1dc3a4cadef67d2695e38/35302db7-7978-49f7-b07b-79df0f23e4b8)

On sketch: https://www.sketch.com/s/add11476-b42d-44cc-a705-8d2bde1f3f69/a/lvzolo
