### ISSUE TITLE
`selectChange` selector not using current flights' changes status

### ISSUE THREAD

**Issue by rpeterman-gp** [PRX/grove.prx.org#228]
### Reproduce

1. Edit a flight on a campaign with multiple flights.
2. Make a change to the title of the flight.
3. Note the save button is now active. DO NOT PRESS THE BUTTON.
4. Click on another flight tab.
5. Note the save button is now disabled.
6 Switch back to the edited flight.
7. Note save button is still disabled, though changes are still properly shown in form field and on tab label.

#### Expected Behavior
Once a valid change has been made to a flight, the save button for the campaign should remain active even when navigated to another unmodified flight.

**Comment by sandikbarr** [comment]
I'm not actually seeing this or able to recreate and that selector does check all flights to see if some have changed. But I am seeing that the newly navigated to flight has a form update go out upon navigation where changed is true, so that's less of a problem but still not awesome.
