### ISSUE TITLE
dashboard date format

### ISSUE THREAD

**Issue by sandikbarr** [PRX/grove.prx.org#240]
Ad-ops would prefer if the date format on the (just flights? not the campaign cards with the short date format?) dashboard were zero padded to have the same amount of digits in all days/months, as is change "7/28/20" to "07/28/20".

**Comment by cavis** [comment]
I kind of think they wanted the dates _everywhere_ to have that format.  Including reports.  But worth checking that.

And worth considering other/future users... sort of a locale thing, right?

**Comment by sandikbarr** [comment]
all dates
