### ISSUE TITLE
Implement Flight statuses

### ISSUE THREAD

**Issue by brandonhundt** [PRX/grove.prx.org#246]
See #206.  After PRX/augury.prx.org#303.

- [x] Remove campaign status field from the campaign form
- [x] Add a flight status field to the flight form before the zones (after the series selection). Simple selectbox. Same states as the campaign had
- [x] Replace the campaign status with the flight state in the flight dashboard.
- [x] Remove campaign status from the campaign cards.
- [x] TODO: what about the dashboard filters/facets?
  - PRX/augury.prx.org#303 will add a "flight status" filter/facet.  But the campaign status filter/facet will disappear.
  - Maybe the status filter isn't valid on the campaign dashboard?

**Comment by cavis** [comment]
NOTE: the "status" filter continues to work on the campaign dashboard.
