### ISSUE TITLE
Validate flight status transitions

### ISSUE THREAD

**Issue by cavis** [PRX/grove.prx.org#247]
After PRX/augury.prx.org#304.

Validate flight status changes adhere to the flows listed in the PRX/dovetail-router.prx.org#83 chart:

![image](https://user-images.githubusercontent.com/1410587/88582166-81419d00-d00b-11ea-92ba-c39b4c438180.png)

(May want to reconsider setting unfulfilled back to active/approved ... but otherwise I think those are pretty accurate).

**Comment by brandonhundt** [comment]
More explanation for the diagram.

If a flight has a draft state [Draft, Hold, or Sold] the user can only change the status to Draft, Hold, Sold or Approved.

If the flight is in an approved state [Approved, Paused] the user can only change the flight status to Paused, Approved, or Cancelled

If the flight is cancelled, the flight status can not be changed. 

Only the system can change a flight from Approved to Completed [either fulfilled or unfulfilled].

Once a flight is in a completed state, it can not be changed by a user.
