### ISSUE TITLE
campaign form, add advertiser as the last field set doesn't show Save button

### ISSUE THREAD

**Issue by sandikbarr** [PRX/grove.prx.org#257]
If the user adds the advertiser as the last field that is set on the campaign form and everything else is valid, the Save button is not shown after the advertiser has been added via the API and the form value is set to the new advertiser uri.

Might be a tricky one. The advertiser is set on the campaign on AddAdvertiserSuccess, but this action has no awareness of the valid state on the campaign form. Prior to setting the advertiser, the form was invalid because advertiser is required.

The work planned in the [Advertiser Metadata](https://github.com/PRX/augury.prx.org/issues/198) Epic makes this functionality obsolete.

**Comment by brandonhundt** [comment]
wontfix. closing
