### ISSUE TITLE
Allocated Priority

### ISSUE THREAD

**Issue by brandonhundt** [PRX/grove.prx.org#260]
User story:

> How might we let Grove users add a new flight to the system that takes priority/allocations over some existing flights but not others.

The plan is to add a `flights.allocation_priority` int field, and use that to order reallocations.  So when you edit a flight, it's going to be allowed to "steal" allocations from overlapping flights with lower priorities.  (But not the same or higher priorities).

Also going to display a list of overlapping flights for convenience - you'll know what you _could_ be stealing from.

Fallout: the designs include "overlapping advertisers", #275 which is moving into the [Advertiser Metadata](https://github.com/PRX/augury.prx.org/issues/198) epic.

**Comment by brandonhundt** [comment]
![DT - Allocated Priority.jpg](https://images.zenhubusercontent.com/5bd1dc3a4cadef67d2695e38/0d79183e-16af-4408-8add-20ef7e938231)

**Comment by cavis** [comment]
Was that a subtle reminder that I should write these tickets @brandonhundt ?

**Comment by brandonhundt** [comment]
Ha. No. I confused this with the design ticket and accidentally closed it before realizing the errors in my ways.

But yes, please write the tickets :)

**Comment by cavis** [comment]
Tickets all created and estimated!  Will prioritize during preening/planning.
