### ISSUE TITLE
Unauthorized creatives show up as blank mp3s

### ISSUE THREAD

**Issue by cavis** [PRX/grove.prx.org#278]
- Create a new campaign, owned by some-group-account
- Create a new creative, owned by some-other-account
- Add creative to flight (may have to use a different user to accomplish this; or just change the DB).
- Go look at flight as original user.

Expected: to see the creative attached, and be able to edit it.

Actual: shows up as a blank mp3 (and there's a 404 in the dev console).

---

Not obvious to me exactly how you can get that creative url, if you're not in the creative.account_id.  But we should do something better!

**Comment by sandikbarr** [comment]
> Expected: to see the creative attached, and be able to edit it.

Stating the obvious, but this doesn't really work as acceptance criteria/requirements for this ticket. It seems we need to show a not found error here because we cannot get the creative and have no way of knowing it's an authorization issue. Related to #271

**Comment by cavis** [comment]
True.  I guess as a baseline, a 404 on a link we followed is an error.  Which should be surfaced somewhere in the UI (even a toast would be fine to start).  It's the silently-continuing-on and showing it as a null/blank-mp3 that's a problem.

From there - we need to decide in Augury how the CreativePolicy auth handles this.  Having access to the Campaign.account_id, but not the Creative.account_id.

**Comment by brandonhundt** [comment]
wontfix. closing.
