### ISSUE TITLE
Flight targets not clearing for new flight

### ISSUE THREAD

**Issue by cavis** [PRX/grove.prx.org#287]
The flight targets state appears to be carrying over from existing flights to new ones.

1. Navigate to an existing flight with a target
2. Click "add a flight"
3. Select the series
4. See the targets section populate with the prior flight's state

Should start with an empty state.

---

Bonus points: when you navigate to the flight form the first time for a series (inventory) ... the targets don't display right away.  A bit jarring to see the form load, and then a second later the "targets" appear.  Would be much nicer to display those upfront (it's all in the flights json), even if the other dropdown options aren't loaded yet.

**Comment by brandonhundt** [comment]
Grove only bug. Closing.
