### ISSUE TITLE
Saving campaign after deleting an unsaved flight should route to campaign form

### ISSUE THREAD

**Issue by rpeterman-gp** [PRX/grove.prx.org#325]
### Reproduce
1. Go to a campaign and click add new flight button.
2. Delete the flight.
3. Save the campaign

#### Expected
App should route to campaign form since previous flight was deleted.

#### What happens
Route stays on deleted flight route, showing flight form in its previous unsaved state.

**Comment by brandonhundt** [comment]
Augury just does this. Closing.
