### ISSUE TITLE
Refactored app template review

### ISSUE THREAD

**Issue by farski** [PRX/grove.prx.org#335]
See PRX/internal#696. Provide the results for this app in this issue.

**Comment by cavis** [comment]
- [x] CPU and memory for all task definitions
- [x] Desired count for all ECS services
- [x] Correct listener rules and priorities
  - **I THINK the Priority should be `!Join` with `"00"` not `"01"`.  At least that's the way other apps do it.**
- [x] All tags
- [x] Stack description
- [x] Log group retention
- [x] Alarms (missing alarms, unnecessary alarms, incorrectly configured alarms, etc)
- [x] Alarm names and descriptions
- [x] Look for anything that look problematic for multi-region (e.g., hard-coded regions, etc)
- [x] Environment variables moved from secrets to the template
  - **Should get AUTH_HOST, AUGURY_HOST, PORT, HOST from the template.  But actually... this app is going away, so maybe just do nothing**.
- [x] Target group health checks and deregistration values
- [x] Missing resource/components (compare to old template)
- [x] TODOs and tktk
