### ISSUE TITLE
Duplicate flight

### ISSUE THREAD

**Issue by cavis** [PRX/grove.prx.org#35]
Client-side duplication of a flight.  Doesn't even require that the flight you're copying is saved - just copies the values out of the form to a new flight.

- [ ] Copy all fields except start/end date
- [ ] Navigate to new (unsaved) flight within campaign

**Comment by cavis** [comment]
Could _maybe_ attempt to tackle this earlier?  After #11.

**Comment by brandonhundt** [comment]
See the design here: https://sketch.cloud/s/On4Gq/a/8qeLQ3
