### ISSUE TITLE
material date range picker

### ISSUE THREAD

**Issue by sandikbarr** [PRX/grove.prx.org#47]
per @brandonhundt:
For the date range selection, is it possible to include the date in one filter field? something along the lines of this (see the 'mobile date range picker) https://material.io/components/pickers/#mobile-pickers
Or
maybe like this, kind of how Google Analytics has the dates (but prettier than the example): https://angularscript.com/material-datetime-range-picker/

* Users can select both start and end dates or leave one side unset/unbounded

**Comment by sandikbarr** [comment]
Official support coming in Q1. We’ll have to upgrade Angular. https://github.com/angular/components/issues/4763

**Comment by brandonhundt** [comment]
Wontfix. Closing.
