### ISSUE TITLE
Dashboard: use unique status colors

### ISSUE THREAD

**Issue by brandonhundt** [PRX/grove.prx.org#50]
Draft: `#B3D9EF`
Approved: `#23C763`
Paused: `#FFC400`
Cancelled: `#E04524`
Hold: `#FF9600`
Sold: `#17C9D3`

**Comment by sandikbarr** [comment]
@brandonhundt Some of the colors above are darker and some are lighter. Given that we are using white text on a colored background for the text labels, we might want to choose a consistent set of darker or lighter backgrounds and have either dark or light color of text in the labels. Here is a screenshot of the application currently with a11y contrast warnings highlighted using [tota11y](https://khan.github.io/tota11y/). The green, blue, orange labels are already pretty low contrast for that size.
![Screen Shot 2019-09-25 at 2 52 26 PM](https://user-images.githubusercontent.com/2250413/65634577-216e0600-dfa4-11e9-971f-580431485291.png)

**Comment by brandonhundt** [comment]
Overall, I like the idea of using brighter colors here from the PRX palatte, if only to break up the gray of the rest of this app. But a11y trumps all. (and I love the a11y feature you are using!)

So, my first question is, is it possible to adjust the text color within each color state (github does this with their labels)?

Because we could use a darker label on brighter backgrounds. But agreed some of the colors still would need adjusting to work.

**Comment by sandikbarr** [comment]
yeah that's totally doable, I was just hoping we could do a consistent light or dark text color for these labels for aesthetic reasons since it's a limited set of colors
