### ISSUE TITLE
Zones dropdown blank after changing tabs

### ISSUE THREAD

**Issue by cavis** [PRX/grove.prx.org#55]
Zones dropdown clears when changing tabs.  Steps:

1. Navigate to a campaign
2. Click on an existing flight tab
3. Change the zone dropdown (add a zone)
4. Save
5. Click on the Campaign tab
6. Click back to the flight tab
7. Flight zones dropdown is now blank

**Comment by pstjean** [comment]
Simpler reproduction:
1. Load campaign.
2. Navigate to existing flight.
3. Zones are blank.

**Comment by pstjean** [comment]
Something related is more rarely happening with flight series, will try to isolate, since it seems like that should come along for the ride here.
