### ISSUE TITLE
Requirements Gathering: What do account permissions look like?

### ISSUE THREAD

**Issue by cavis** [PRX/grove.prx.org#67]
@brandonhundt commented on [Mon Oct 21 2019](https://github.com/PRX/id.prx.org/issues/151)

Who are the users that need accounts? (advertisers)

(Next step, what do permissions look like across Publish, Grove, Metrics, etc)

**Comment by brandonhundt** [comment]
Adding @cavis as a co-assignee:

1. What Shows you have access to?
2. What Applications you have access to?
3. What Roles do you have within the applications?
4. How do we simplify the terminology used in accounts?

Meeting notes from discussion with Paloma and Kate: https://docs.google.com/document/d/1Ystq2dMtD_W8IyfJWG_FsXljI2S0FGk8VyNa9cNpQv8/edit

**Comment by brandonhundt** [comment]
Actually, I'm going to open a new ticket in ID and close this one.
