### ISSUE TITLE
flight start/end date validation

### ISSUE THREAD

**Issue by sandikbarr** [PRX/grove.prx.org#75]
- [x] Flight dates should be validated so that end at must be greater than start at. User should not be able to Save the form unless valid.
- [ ] If flight dates are changed, validate that the start and end date fall within the range of actuals that have been served
- (are there any other validation rules like not setting up new flights in the past or editing flights to be further in the past than has already run?)

**Comment by sandikbarr** [comment]
I'm guessing the remaining work on the material date range picker #47 will clean this up

**Comment by cavis** [comment]
Update: should validate a running flight (one with actuals coming in) doesn't move its start date.  The frontend part of PRX/augury.prx.org#221.  (I think you can just check if flight.startAt < now() ... don't let them change it?)
