### ISSUE TITLE
Campaign/Flight form discard on navigation

### ISSUE THREAD

**Issue by sandikbarr** [PRX/grove.prx.org#77]
If the user attempts to navigate away from the Campaign/Flight form when there are unsaved changes, they should be presented with a dialog to save or discard those changes.

~A discard button should also be added (location?) to discard any unsaved changes in the campaign and flight forms. The discard button is enabled when the form has been changed (similar to Save, but for Save the form should also be valid.)~ Discard button moved to #277 

Currently what happens with the campaign state is if the user navigates away and then back, there is a flash of content with the changes then the actually persisted data populates in the form as it comes in from the API. The campaign store state management does not seem to retain the changes after the user navigates away.

**Comment by pstjean** [comment]
Do the same thing for `/campaign/new`

**Comment by brandonhundt** [comment]
Closed in Grove-on-Augury
