### ISSUE TITLE
Forecasting for new series

### ISSUE THREAD

**Issue by cavis** [PRX/grove.prx.org#80]
As an ad/ops admin, I would like to generate a forecast for a new show.

What if the forecast is way wrong, or we don't want to enforce it?  Use cases to consider:

- Whole season drops at once (a la S-Town).  Forecast is either non existent (no episodes) or way off (hard to predict what will happen in R)
- Brand new podcast with no metrics.  How do we manually enter expected downloads-per-episode into the system?  (Or do we?)
- Can we remove the cap from a flight?  So if there's nothing else to serve ... just keep serving this flight.  Related: we want to give 100% of this ad-zone to 1 sponsor, for this date range.

**Comment by brandonhundt** [comment]
Epic complete.
