### ISSUE TITLE
Campaign dashboard goal/actuals

### ISSUE THREAD

**Issue by cavis** [PRX/grove.prx.org#82]
Needs PRX/augury.prx.org#139.  Add the summed-up flight goals / actuals to the dashboard.

![image](https://user-images.githubusercontent.com/1410587/68872621-91069480-06bb-11ea-8ed4-3048c1f91f9c.png)

**Comment by brandonhundt** [comment]
Instead of the label "impressions served", lets use the label "inventory served"

thanks.
