### ISSUE TITLE
Handle Augury allocation validation errors

### ISSUE THREAD

**Issue by pstjean** [PRX/grove.prx.org#90]
On validation error, decode the JSON and display what went wrong. If it failed to allocate, re-run the allocation-preview to get the error displaying on the table. For other validation errors, display them somewhere global.

HAL handlers don't currently pass back the body when there's a response code > 300. These handlers are in Styleguide, so we need to either handle with a 200 response code, or make some changes in Styleguide to allow passing through the body of a non-200.

**Comment by sandikbarr** [comment]
dup of #68
