### ISSUE TITLE
Implement Uncapped Flights

### ISSUE THREAD

**Issue by brandonhundt** [PRX/grove.prx.org#92]
Needs PRX/augury.prx.org#173.

* Lower priority than capped flights (uncapped flights = you get what you get)
* Warn users that there’s an uncapped flight also targeted, and that capped flight will eat into that inventory. (status not warning). Can be displayed under the table.
* Use Material's slide toggle: https://material.angular.io/components/slide-toggle/overview
* BONUS: Clean up spacing around goal fields.
* If toggled, the goal/minimum fields will not be present.
* If toggled, the “Allocated” column in the table changed to “Expected”, and it would display the day over day counts of “available_count - SUM(other_allocations)”

![cap-toggle](https://user-images.githubusercontent.com/369739/70573716-27699100-1b68-11ea-9bed-6ccb600d76e2.jpg)

**Comment by sandikbarr** [comment]
Not sure the API lets you save a flight without a goal at this point, maybe if uncapped, will have to check.

**Comment by cavis** [comment]
Checking the Augury code... looks like there's a ["uncapped"](https://github.com/PRX/augury.prx.org/blob/master/app/representers/api/flight_representer.rb#L15) param on the flight now.  And if you set that to true, it validates that the [goal must be 0](https://github.com/PRX/augury.prx.org/blob/master/app/models/flight.rb#L137).

**Comment by sandikbarr** [comment]
Is it cool if I pull the other flight allocations from the `/inventory/availability` API? That's where allocations come from until the API refactoring is done and we can move all the inventory numbers to be off the flights.

**Comment by cavis** [comment]
I think so.  We still want to display availability and actuals even if your daily allocations are 0.

I'd assume with that API refactoring (PRX/augury.prx.org#205), you'll basically get the uncapped flight as:

```
{
  name: "My Flight Name",
  totalGoal: 0,
  uncapped: true,
  days: [
    {date: '2020-02-22', actuals: 123, allocated: 0, availability: 789}
    ...
   ]
}
```
```

**Comment by sandikbarr** [comment]
nice. Since those are embedded in flights we probably shouldn't even need to zoom all the flights and the numbers to calculate the uncapped flight should just be available from the original campaign + flights request. thank you!

**Comment by cavis** [comment]
I may try to pull this in this sprint, if i can.
