### ISSUE TITLE
Re-design Zonebased scorecards in mockups to hold Show level data.

### ISSUE THREAD

**Issue by brandonhundt** [PRX/grove.prx.org#93]
UPDATE: Editing to be a redesign ticket after discussion with @cavis. 

Look at Show level stats instead of zone-based stats.

-------

I think there is some confusion around what we are calling different sections of the dashboard, this is my bad. One piece of the dashboard we still to implement are the Zone based scorecards:

![Screen Shot 2019-12-16 at 9.18.49 AM.png](https://images.zenhubusercontent.com/5bd1dc3a4cadef67d2695e38/683ba0b1-a972-434c-b0d3-6fe1dcea8604)

1. When a user filters by a zone from the dashboard, this zone-based scorecard should appear, containing a roll up of data targeting the zone. 
2. If multiple zones are filtered, multiple zone scorecards should appear. 
3. House zones do NOT have a zone scorecard.

Sketch file: https://sketch.cloud/s/On4Gq/a/OZJzLv

**Comment by cavis** [comment]
I find these numbers a bit confusing.  What timeframe are they representing?  It appears to be combining past and future numbers in a way that feels awkward to me.  (Forecasted/sold refer to some future time window, where actuals refer to the past).

**Comment by brandonhundt** [comment]
Good questions:

The numbers would represent the timeframe picked by the user. If there isn't a timeframe, I don't think we should show these numbers.

But the idea is that in a given timeframe there is a forecasted total for a show if its in the future or in the past (a historical forecast). For example, we can use the TED Talks Daily forecast from Oct. This is were we can see a high level report of what was forecast vs what was actual vs what was sold.

If the date is in the future we won't be able to display actuals (like on the flight form) but may have a forecast available, and we should display that, along with any reserved inventory.

"Sold" represents the allocated impressions. I should update this to say "Reserved".

I hope this makes more sense.

**Comment by cavis** [comment]
Ah, okay.  So those dates we're filtering the Campaigns by also applies to these.  That makes more sense.

Yeah, I agree "sold -> reserved" makes more sense.  Or we can use the actual Augury terminology: "Allocated".

My other comments:

- "Downloads" doesn't make a ton of sense in the context of a single zone.  When would the number of downloads the podcast as a whole differ from the "post_1" impressions?
  - I guess there's the IAB2 dropoff rate ... where something < 1% of clients never download far enough to count the postroll.
  - Or maybe you're counting layouts of the show that don't have a "post_1" at all?  Like maybe there's an "ad free promo" template that has no postrolls.  That seems a bit weird to display here.
- Each "zone" is specific to a show.  So we'd probably want to list them all separately, to make any sense.  In practice, that means the dashboard might have many "Preroll 1"s ... unless you filter your list to a single podcast.
  - (Unless you're suggesting we rollup many podcasts data by zone_name)
- Eventually, there may be a ton of these if you're looking at many podcasts.  Like > 20.  Could get into paging issues - we need to page the campaigns, and page the zone-scorecards.
- We'll need to build the Augury APIs for "zone actuals".  Currently we only have "flight" and "campaign" actuals.

**Comment by brandonhundt** [comment]
Thanks @cavis, I'm going to rename this ticket so its more of a design ticket than a implementation ticket. We've learned a lot more since these were originally designed.

**Comment by brandonhundt** [comment]
Increasing priority after talking with the Ad/ops team on 02/27/2020

- Ability to see availability across an entire show and the campaigns 
-- “This campaign always needs to run” so that manual intervention can occur. 
-- Use the Inventory dashboard:
-- Add actuals, availability and allocated columns
-- Ensure there are totals on the table. (in the header)
-- Can breakdown by date
-- View by dates and not by flights. 

Also add in scorecards with Forecast, Actuals, Availability and Allocations for selected filters (when a zone is selected)

**Comment by brandonhundt** [comment]
Not doing this anymore. Closing.
