### ISSUE TITLE
Advanced Targeting

### ISSUE THREAD

**Issue by brandonhundt** [PRX/grove.prx.org#96]
Geolocation
Episode Targeting
Keyword Targeting
Non-explicit
Unique per advertiser/campaign

More info to come. 

Need user stories for each type of target

Some info here: https://docs.google.com/document/d/15Sskvl8XG7HYisgc08XFgUPOh0rQ-bCdMiEuXwtxb7I/edit#heading=h.n8eg1w3l3wld

**Comment by cavis** [comment]
Moving to PRX/dovetail-router.prx.org#41
