### ISSUE TITLE
Must refresh required in order to set the owner field

### ISSUE THREAD

**Issue by brandonhundt** [PRX/grove.prx.org#99]
1. Create a new campaign in a new browser session: https://grove.staging.prx.tech/campaign/new
2. In the Campaign Tab, fill in required fields
3. Note that the Owner field does not have any options available to select
4. Add a flight
5. Click on the Campaign tab and select the Rep's name in the input. 
6. Try adding a name that is not the same as the Rep. (can't)
6. Continue on with the campaign.

Expected:
1. Create a new campaign
2. In the Campaign Tab, fill in required fields
3. Easily add the owner field without leaving the tab. The owner might be separate from the Rep, so this should include a typeahead option OR just be a standard textfield. 
4. Continue on with the campaign.

**Comment by sandikbarr** [comment]
The campaign owner field cannot be a typeahead. The campaign owner is an account from id.prx.org. I don't think we want to start adding accounts from Grove.

Those accounts do seem to be slow to load and we've seen some issues there with loading order and setting the typeahead values.
